### ISSUE TITLE
Sprite Kit version crashes

### ISSUE THREAD

**Issue by lorenzOliveto** [ryang1428/ShootingStars#1]
Tapping on the Sprite Key button the app crashes because the dotEmitter variable is nil. 

Changing this line: 
`SKEmitterNode *dotEmitter =  [NSKeyedUnarchiver unarchiveObjectWithFile:[[NSBundle mainBundle] pathForResource:@"Asterisk" ofType:@"sks"]];`
To this:
`SKEmitterNode *dotEmitter =  [NSKeyedUnarchiver unarchiveObjectWithFile:[[NSBundle mainBundle] pathForResource:@"AsteriskParticle" ofType:@"sks"]];`
Everything works as expected.

**Comment by ryang1428** [comment]
Thanks, fixed!
